### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by ttxoox** [ClaudeLi/DLNA_UPnP#1]
最近我也在做DLNA方面的功能，运行博主的程序后，不能播放音乐，控制台输出xmlString = <s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>401</errorCode><errorDescription>Invalid Action</errorDescription></UPnPError></detail></s:Fault>，显示是无效的action，请问这是什么原因？另外，在搜索设备时，时常会出现udpsocket 关闭的信息，该如何解决？

**Comment by ClaudeLi** [comment]
之前为了做类似 腾讯视频的视频投屏 demo中没有加入 s:Client 方法 ，upnp支持的方法你可以查看设备信息xml文件的 <SCPDURL>中查看 ，你可以在demo中加上自己需要的方法 。 关于udpsocket搜索设备 有点bug，我写demo的时候就在 - start方法里 加了15秒之后关闭，你可以去掉，这样可能会有bug 同一个设备返回很多次。

**Comment by ttxoox** [comment]
你好，今天看了一天，算是弄出了搜索设备功能。你说的s:Client是指什么？不是很懂。或者你能不能说一下搜索到设备后应该怎么做。我现在是想把手机上的歌，推送到设备上面去，让设备播放。由于你的demo不能播放，我也不知道你的是怎么弄的，看你的代码好像和我的需求差不多。另外能否给个QQ或者微信，希望详细学习一下。谢谢。

**Comment by ClaudeLi** [comment]
727147910
