### ISSUE TITLE
关于License

### ISSUE THREAD

**Issue by wyzhang86** [ClaudeLi/DLNA_UPnP#13]
你好，我们用到了这个代码，但是这个代码没有license声明。能否提供一个license给我们，或者你们是不是可以增加license声明。谢谢！

**Comment by ClaudeLi** [comment]
👌 我明天会上传license声明




| |
ClaudeLi
邮箱：claudeli@yeah.net
|

Signature is customized by Netease Mail Master

在2019年04月11日 19:07，ivan 写道：

你好，我们用到了这个代码，但是这个代码没有license声明。能否提供一个license给我们，或者你们是不是可以增加license声明。谢谢！

**Comment by ClaudeLi** [comment]
@wyzhang86 已添加license
