### ISSUE TITLE
播放视频问题

### ISSUE THREAD

**Issue by JackTedo** [ClaudeLi/DLNA_UPnP#3]
你好，不修改代码，只是修改视频url地址，运行博主的程序后，能播放有些视频到电视（比如：http://v.tiaooo.com/llbizosAzGhJPXC0H4AHLTGHl42W ），有些视频就不能播放。

出现的错误有几种。
1. 播放youtube的视频错误。
xmlString = <s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode><errorDescription>Transition not available</errorDescription></UPnPError></detail></s:Fault>
2. 播放 视频url类似 http://192.168.1.139:8080/IMG_1380.m4v， 电视端显示不支持该类型。
3. 还有是显示错误的mime type。

不知道如何做到支持几种基本的视频类型的播放？

**Comment by ClaudeLi** [comment]
youtube 的视频 需要翻墙才能播放；播放视频需要在同一局域网下；对于errorCode 你可以参照https://eliyar.biz/DLNA_with_iOS_Android_Part_2_Control_Using_SOAP/ ；我是看到这篇博客的介绍没有OC版的 写了这个demo 做个参考吧

**Comment by JackTedo** [comment]
非常感谢ClaudeLi 。正好现在在国外，youtube不用翻墙。播放图片很好没问题，播放网络视频只有 http://v.tiaooo.com/llbizosAzGhJPXC0H4AHLTGHl42W  这个能行，换了几个别的都不行。我再学习学习看能不能找到问题。
