### ISSUE TITLE
真机无法搜到设备

### ISSUE THREAD

**Issue by MQL9011** [ClaudeLi/DLNA_UPnP#6]
我的真机(iOS11 ) 和 模拟器都在同一个局域网,同一个网段下,模拟器可以搜到设备,可以投屏播放.
但是真机就无法搜到设备,进入搜索页面,控制台只输出了
`[CLUPnPServer.m in line 109] => udpSocket关闭`
请问这个怎么处理?

**Comment by MQL9011** [comment]
好吧,是我没开网络权限...然后只请求socket的话是不会提醒用户打开网络权限的

**Comment by ChinaKeep** [comment]
添加权限依然报错  sendto: -1 发送没有成功
